Porting to GHEX 0.2.0 + fixes for multiple devices
GridTools/gtbench pull request #77
Opened 2022-07-21 00:33 UTC by bettiolm

- `ghex_comm` runtime ported to ghex 0.2.0, using oomph as transport library.
- fixed an issue that caused `detected error differences between the runs` when using the `ghex_comm` runtime on multiple devices. It was due both to streams synchronization issues and to the choice of the default set-device strategy.
- GHEX code does not depend anymore on the `gridtools::_impl` namespace.
- NOTE: semantics of the `--device-mapping` option has changed: it now accepts only one device id per rank, meaning that different threads on the same rank must use the same device.
- AMD GPUs fixes are not included, and will follow shortly.

2022-07-28 11:00 UTC, bettiolm commented
AMD GPUs support for `ghex_comm` runtime has been added. The only feature that cannot be fully transferred to AMD GPUs is the `--default-stream=per-thread` compile option. It seems the feature will be supported in future versions of the clang compiler (see e.g. https://github.com/llvm/llvm-project/blob/llvmorg-16-init/clang/include/clang/Driver/Options.td#L981 , from which it seems it will be included in `clang-16`).

2022-07-28 12:02 UTC, fthaler requested changes
Thank you very much for this work! I added some comments about the `// TODOs` still in the PR.

2022-07-28 12:48 UTC, bettiolm commented on src/runtime/ghex_comm/run.cpp
> +          domain, storage, {halo, halo, 0}); // TO DO: device id
Just a leftover. It has been fixed on the GHEX side. We don't pass the device id here, and ghex uses the current device id as default value. I updated the comment.

2022-07-28 13:47 UTC, bettiolm commented on src/runtime/ghex_comm/run.cpp
> +  context_ptr_t m_context; // TO DO: is a pointer still needed here?
Sure, the context is needed. Probably I was not sure whether to store the pointer here. I removed the comment.

2022-07-28 13:55 UTC, bettiolm commented on src/runtime/ghex_comm/run.cpp
> +// TO DO: barrier
Shouldn't be needed anymore with the new implementation. The benchmark is working even without. Let me run one last test to make sure.

2022-07-29 09:06 UTC, fthaler commented
Looks good to me as soon as the barrier question is resolved and respective comments are cleaned. But as I do not have much knowledge of GHEX, maybe @boeschf can also do a brief review?

2022-07-29 12:36 UTC, boeschf approved these changes

2022-07-29 14:34 UTC, bettiolm commented on src/runtime/ghex_comm/run.cpp
> +// TO DO: barrier
I eventually restored the barrier.

2022-07-29 14:36 UTC, bettiolm commented on src/runtime/ghex_comm/run.cpp
> +  // TO DO: m_barrier;
Done

2022-07-29 14:36 UTC, bettiolm commented on src/runtime/ghex_comm/run.cpp
> +    // TO DO: m_barrier(num_sub_domains) {
Done

2022-07-29 14:36 UTC, bettiolm commented on src/runtime/ghex_comm/run.cpp
> +    // TO DO: m_barrier(comm);
Done

2022-07-29 14:38 UTC, bettiolm commented
@fthaler, I addressed your comments and reintroduced the barrier, as in the original implementation.

2022-08-02 05:25 UTC, fthaler approved these changes

2022-08-02 05:25 UTC, fthaler commented
@bettiolm Thank you very much!

2022-08-02 05:26 UTC, merged